version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0812
    ports:
      - 5432:5432
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - backend

  python-backend:
    build: ./MVP_Arquitetura_Back
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - frontend
      - backend

  express-api:
    build: ./MVP_ARQUITETURA_S3
    ports:
      - "3003:3003"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - frontend
      - backend

  react-app:
    build: ./MVP_ARQUITETURA_FRONT
    ports:
      - "3000:80"
    env_file:
      - .env
    depends_on:
      - express-api
      - python-backend
    networks:
      - frontend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge